( define  (domain network_final)
(:requirements :strips :typing)
(:types webserver cvevul sqlserver adversary accesspoint connection software version file config code loginpage link attack location)
(:predicates

    (access-point-web ?Acc1 - accesspoint)
    (access-point-sql ?Acc2 - accesspoint)
    (access-point-admin ?Acc3 - accesspoint)
    (access-point-dns ?Acc5 - accesspoint)
    (access-point-ftp ?Acc4 - accesspoint)
    (remote-access ?Internet - connection)
    (attacker ?Attacker - adversary)
    
    (has-connection-web-to-sql ?web - webserver ?sql - sqlserver)
    (has-connection-sql-to-web ?sql - sqlserver ?web - webserver)
                                                          ;;;;;;;;;; Predicates for Web Server ;;;;;;;;;;;;

    ;(reach-to-web ?web - webserver)
    ;(connected-to-web ?web - webserver)
    (web-server ?web - webserver)
    (connected-to ?web - webserver)
    (has-connected-to-web ?web - webserver ?Attacker - adversary)
    (access-to-web-software ?software - software ?web - webserver ?Attacker - adversary)
    (web-software ?Software - software)
    (web-version ?Version - version)
    (configuration ?config - config)
    (execute-file-in-config ?File - file ?config - config ?web - webserver)
    (execute-code ?web - webserver ?Code - code ?Attacker - adversary)
    (web-file ?File - file)
    (web-code ?Code - code)
    (compromised-web-server ?compweb - webserver)
                                                          ;;;;;;;;;; Predicates for Database Server ;;;;;;;;;;;;;
    
    (sql-server ?sql - sqlserver)
    (has-connected-to-sql ?sql - sqlserver ?Attacker - adversary)
    (sql-software ?Software - software)
    (sql-version ?Version - version)
    (access-to-sql-software ?software - software ?sql - sqlserver ?Attacker - adversary)
    (access-to-sql-server ?sql - sqlserver ?Attacker - adversary ?Internet - connection)
    (sql-file ?File - file)
    (use-software ?Software - software ?sql - sqlserver ?Attacker - adversary)
    (sql-injection ?File - file ?Software - software ?sql - sqlserver ?Attacker - adversary)
    (login-page ?Page - loginpage)
    (access-login-page-via-software ?Page - loginpage ?Software - software ?sql - sqlserver)
    (access-login-field ?Page - loginpage ?sql - sqlserver ?Attacker - adversary)
    (sql-code ?Code - code)
    (execute-code-in-login-feild ?Code - code ?Page - loginpage ?sql - sqlserver)
    (compromised-sql-server ?compsql - sqlserver)
    ;(move-to-database ?sql - sqlserver)
    ;(access-granted-to-db ?sql - sqlserver ?Acc1 - accesstoken)
    ;(reach-to-db ?sql - sqlserver)
    ;(connected-to-db ?sql - sqlserver)
    
                                                                ;;;;;;;;;; Predicates for APACHE Web Server ;;;;;;;;;;;;
    ;(apache-server ?apache - webserver)
    (apache-software ?Software - software)
    (apache-version ?Version - version)
    (access-to-apache-software ?Software ?Version ?apache ?Attacker)
    (apache-path ?Url - link)
    (apache-attack ?Attack - attack)
    (apache-file ?File - file)
    (map-url-to-files ?Attack - attack ?Url - link ?File - file ?apache - webserver ?Attacker - adversary)
    (apache-location ?Directory - location)
    (access-to-directories ?Directory - location ?apache - webserver ?Attacker - adversary) 
    (apache-code ?Code - code)
    (execute-code-in-file ?Code - code ?File - file ?apache - webserver)
)

%OPERATORS%

)